version: '3'

services:
  nginx:
    image: nginx:1.23-alpine
    ports:
      - '8080:80'
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./out:/usr/share/nginx/html
